[package]
name = "rusty_color"
version = "0.1.0"
authors = ["john"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample = "0.10.0"
hound = "3.4.0"
image = "0.23.4"
rustfft = "3.0.1"
